//! Per-node firmware project and master flashing script generation.
//!
//! Every shard gets a self-contained firmware skeleton (Rust by default —
//! memory-safe firmware is the whole point of the platform; C++ available)
//! plus a JSON manifest of exactly which tensors, ops, and KV-slice that
//! node owns. The coordinator gets parallel `esptool` flash scripts (`.sh`
//! + `.ps1`) so a 16-node fleet flashes over USB hubs in one command.
//!
//! Templates are string-built today; migrating them to `askama` templates
//! is tracked in `todo.md`.

use serde::{Deserialize, Serialize};

use crate::partition::PartitionPlan;

/// Firmware language to emit.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum FirmwareLang {
    /// Rust (`esp-hal` / `no_std`).
    Rust,
    /// C++ (`ESP-IDF`), for teams already invested there.
    Cxx,
}

impl FirmwareLang {
    /// Source file extension.
    pub fn ext(self) -> &'static str {
        match self {
            Self::Rust => "rs",
            Self::Cxx => "cpp",
        }
    }

    /// Language banner used in generated headers.
    pub fn banner(self) -> &'static str {
        match self {
            Self::Rust => "rust",
            Self::Cxx => "c++",
        }
    }
}

/// Inputs describing the compile job.
#[derive(Debug, Clone)]
pub struct FirmwareContext {
    /// Model name baked into manifests.
    pub model_name: String,
    /// Target board string passed through to flash tooling.
    pub board: String,
    /// Source language.
    pub lang: FirmwareLang,
}

/// One emitted file (path relative to an output directory).
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct GeneratedFile {
    /// Relative path, e.g. `firmware/node_00/src/main.rs`.
    pub path: String,
    /// Full file contents.
    pub contents: String,
}

/// Per-node shard manifest embedded as JSON next to the firmware source.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ShardManifest {
    /// Model being deployed.
    pub model: String,
    /// Board identifier.
    pub board: String,
    /// Swarm node index.
    pub swarm_node: usize,
    /// IR node names owned by this node.
    pub nodes: Vec<String>,
    /// Weight bytes owned.
    pub weight_bytes: u64,
    /// Reserved KV-cache bytes.
    pub kv_cache_bytes: u64,
}

/// Generate firmware sources, manifests, and master flash scripts.
///
/// Emits, relative to an output root:
///
/// ```text
/// firmware/node_00/src/main.rs      (or main.cpp)
/// firmware/node_00/manifest.json
/// flash.sh
/// flash.ps1
/// ```
pub fn generate(
    graph: &tpt_crucible_common::Graph,
    plan: &PartitionPlan,
    ctx: &FirmwareContext,
) -> Vec<GeneratedFile> {
    let mut files = Vec::new();

    for shard in &plan.shards {
        let dir = format!("firmware/node_{:02}", shard.swarm_node);
        let node_names: Vec<String> = shard
            .graph_nodes
            .iter()
            .filter_map(|id| graph.get_node(*id).map(|n| n.name.clone()))
            .collect();

        let manifest = ShardManifest {
            model: ctx.model_name.clone(),
            board: ctx.board.clone(),
            swarm_node: shard.swarm_node,
            nodes: node_names.clone(),
            weight_bytes: shard.weight_bytes,
            kv_cache_bytes: shard.kv_cache_bytes,
        };
        files.push(GeneratedFile {
            path: format!("{dir}/manifest.json"),
            contents: serde_json::to_string_pretty(&manifest)
                .expect("manifest serialization is infallible"),
        });

        let src_name = match ctx.lang {
            FirmwareLang::Rust => "src/main.rs",
            FirmwareLang::Cxx => "src/main.cpp",
        };
        files.push(GeneratedFile {
            path: format!("{dir}/{src_name}"),
            contents: render_source(ctx, shard.swarm_node, &node_names),
        });
    }

    let ports: Vec<String> = plan
        .shards
        .iter()
        .map(|s| format!("/dev/ttyUSB{}", s.swarm_node))
        .collect();
    files.push(GeneratedFile {
        path: "flash.sh".into(),
        contents: render_flash_sh(plan, ctx, &ports),
    });
    files.push(GeneratedFile {
        path: "flash.ps1".into(),
        contents: render_flash_ps1(plan, ctx, &ports),
    });

    files
}

fn render_source(ctx: &FirmwareContext, node: usize, node_names: &[String]) -> String {
    let manifest_lines: String = node_names.iter().map(|n| format!("  - {n}\n")).collect();
    match ctx.lang {
        FirmwareLang::Rust => format!(
            "// Auto-generated by tpt-crucible-alloy — do not edit by hand.\n\
             // Model : {model}\n\
             // Board : {board}\n\
             // Node  : {node:02}\n\
             // Ops owned:\n\
             {manifest_lines}\n\
             #![no_std]\n\
             #![no_main]\n\n\
             // TODO(alloy-executor): wire this skeleton into the generated\n\
             // weight blob and the heartbeat loop (todo.md).\n",
            model = ctx.model_name,
            board = ctx.board,
            node = node,
            manifest_lines = manifest_lines,
        ),
        FirmwareLang::Cxx => format!(
            "// Auto-generated by tpt-crucible-alloy — do not edit by hand.\n\
             // Model: {model} | Board: {board} | Node {node:02}\n\
             // Ops owned:\n{manifest_lines}\n\
             int main() {{ return 0; }}\n",
            model = ctx.model_name,
            board = ctx.board,
            node = node,
            manifest_lines = manifest_lines,
        ),
    }
}

fn render_flash_sh(plan: &PartitionPlan, ctx: &FirmwareContext, ports: &[String]) -> String {
    let mut s = String::from(
        "#!/usr/bin/env bash\n# Master flashing script - parallel per-node esptool jobs.\nset -euo pipefail\n\n",
    );
    s.push_str(&format!(
        "MODEL=\"{}\"\nBOARD=\"{}\"\n\n",
        ctx.model_name, ctx.board
    ));
    s.push_str("flash_one() {\n  local port=$1 idx=$2\n  esptool.py --chip \"$BOARD\" --port \"$port\" --baud 921600 \\\n    write_flash 0x0 \"firmware/node_${idx}/firmware.bin\"\n}\n\n");
    for (i, port) in ports.iter().enumerate() {
        s.push_str(&format!(
            "flash_one \"{port}\" {:02} &\n",
            plan.shards[i].swarm_node
        ));
    }
    s.push_str("wait\n");
    s
}

fn render_flash_ps1(plan: &PartitionPlan, ctx: &FirmwareContext, ports: &[String]) -> String {
    let mut s = String::from(
        "# Master flashing script (PowerShell) - parallel per-node esptool jobs.\r\n\r\n",
    );
    s.push_str(&format!(
        "$Model = \"{}\"\r\n$Board = \"{}\"\r\n\r\n",
        ctx.model_name, ctx.board
    ));
    s.push_str("$jobs = @(\r\n");
    for (i, port) in ports.iter().enumerate() {
        s.push_str(&format!(
            "  @{{ Port = \"{port}\"; Index = \"{idx:02}\" }},\r\n",
            idx = plan.shards[i].swarm_node
        ));
    }
    s.push_str(")\r\n\r\n$jobs | ForEach-Object {\r\n  Start-Job -ArgumentList $_.Port, $_.Index, $Board -ScriptBlock {\r\n    param($port, $idx, $board)\r\n    esptool.py --chip $board --port $port --baud 921600 write_flash 0x0 \"firmware/node_$idx/firmware.bin\"\r\n  }\r\n}\r\n\r\nGet-Job | Wait-Job\r\n");
    s
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::partition::{self, PartitionOptions};
    use crate::topology::Topology;
    use tpt_crucible_common::{DType, Graph, NodeId, Op, Tensor, TensorDesc};

    fn sample() -> (Graph, PartitionPlan) {
        let mut g = Graph::new("tinyllama-sil");
        let x = g.push(
            "",
            Op::Input(TensorDesc::new(vec![1, 8], DType::F32)),
            Vec::<NodeId>::new(),
        );
        let w = g.push(
            "blk.0.attn_q.weight",
            Op::Constant {
                tensor: Tensor::zeros(TensorDesc::new(vec![8, 8], DType::F16)),
            },
            Vec::<NodeId>::new(),
        );
        let y = g.push("", Op::MatMul, vec![x, w]);
        let out = g.push("", Op::Output { name: "out".into() }, vec![y]);
        g.mark_output(out);
        let topo = Topology::homogeneous(2, "esp32s3", 8 << 20);
        let plan = partition::partition(&g, &topo, &PartitionOptions::default()).unwrap();
        (g, plan)
    }

    fn ctx(lang: FirmwareLang) -> FirmwareContext {
        FirmwareContext {
            model_name: "tinyllama-sil".into(),
            board: "esp32s3".into(),
            lang,
        }
    }

    #[test]
    fn emits_manifest_source_and_both_flash_scripts() {
        let (g, plan) = sample();
        let files = generate(&g, &plan, &ctx(FirmwareLang::Rust));
        let paths: Vec<&str> = files.iter().map(|f| f.path.as_str()).collect();
        assert!(paths.contains(&"flash.sh"));
        assert!(paths.contains(&"flash.ps1"));
        assert_eq!(
            paths
                .iter()
                .filter(|p| p.ends_with("manifest.json"))
                .count(),
            plan.shards.len()
        );

        let src_path = format!("firmware/node_{:02}/src/main.rs", plan.shards[0].swarm_node);
        let src = files.iter().find(|f| f.path == src_path).unwrap();
        assert!(src.contents.contains("no_std"));
        assert!(src.contents.contains("tinyllama-sil"));

        let flash = files.iter().find(|f| f.path == "flash.sh").unwrap();
        assert!(flash.contents.contains("esptool.py"));
        assert!(flash.contents.contains("write_flash"));

        let ps1 = files.iter().find(|f| f.path == "flash.ps1").unwrap();
        assert!(ps1.contents.contains("esptool.py"));
        assert!(ps1.contents.contains("Start-Job"));
    }

    #[test]
    fn cxx_language_changes_extension_and_body() {
        let (g, plan) = sample();
        let files = generate(&g, &plan, &ctx(FirmwareLang::Cxx));
        let cpp = files
            .iter()
            .find(|f| f.path.ends_with("main.cpp"))
            .expect("c++ source emitted");
        assert!(cpp.contents.contains("int main()"));
        assert_eq!(FirmwareLang::Cxx.banner(), "c++");
        assert!(!files.iter().any(|f| f.path.ends_with("main.rs")));
    }

    #[test]
    fn manifests_are_valid_json_with_expected_fields() {
        let (g, plan) = sample();
        let files = generate(&g, &plan, &ctx(FirmwareLang::Rust));
        let mf = files
            .iter()
            .find(|f| f.path.ends_with("manifest.json"))
            .unwrap();
        let parsed: ShardManifest = serde_json::from_str(&mf.contents).unwrap();
        assert_eq!(parsed.model, "tinyllama-sil");
        assert_eq!(parsed.board, "esp32s3");
        assert!(parsed.nodes.contains(&"blk.0.attn_q.weight".to_string()));
    }
}
